### ISSUE TITLE
start/end positions not respected when accessing cram files

### ISSUE THREAD

**Issue by chrisamiller** [alimanfoo/pysamstats#103]
If I take a short bam file (about 10000 bp of sequence on chromosome 1) and run the following command on it, I get the expected number of bases (151 bp read length * 2 = 302) 
```
pysamstats -f $ref_fasta --type mapq --chromosome chr1 --start 11565 --end 11566 test.bam | wc -l
302
```
If I take that same bam and convert it to cram, then run the identical command, I get results for every position in my small cram file:
```
pysamstats -f $ref_fasta --type mapq --chromosome chr1 --start 11565 --end 11566 test.cram | wc -l
10166
```

Obviously, this is a much more severe problem when trying to look at only a handful of positions in a large WGS cram file (and getting millions of positions returned!).  Any suggestions for why this occurs and how it could be remedied? 

This is all being tested in the [mgibio/mapq0-filter:v0.3.1](https://hub.docker.com/u/mgibio/) docker container, which is currently on Version: 1.1.2 (pysam 0.15.0).  Happy to share a small bam that reproduces the problem if that would be helpful.

**Comment by chrisamiller** [comment]
Upgrading to pysam 0.15.4 fixed the issue, although now I'm seeing warnings like the following: 
```
/usr/local/lib/python3.6/dist-packages/pysamstats/util.py:27: UserWarning: multiple_iterators not implemented for CRAM
  it = (getter(rec) for rec in recs)
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/6aef897c3d6ff0c78aff06ac189178dd": Protocol not supported
```
Some searching leads me to believe that this is an underlying htslib issue with auto-locating the cram reference, and it seems as though it can be safely ignored.  

I'll go ahead and close this up, since it's a pysam/htslib issue, not one with pysamstats.  Thanks again for a useful tool!

**Comment by alimanfoo** [comment]
Thanks @chrisamiller, no worries.
