### ISSUE TITLE
[Installation issue] _frozen_importlib:219: RuntimeWarning: pysam.libcalignedsegment.PileupColumn size changed, may indicate binary incompatibility. Expected 72 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by matthpich** [alimanfoo/pysamstats#105]
Hi,
Your package is awesome and it has been running just well until recently I tried to install it on Ubuntu on Windows and CentOS7.
Attempting a pip install (after updating pip and wheel with "python -m pip install --upgrade pip setuptools wheel"), I get :

```
> pip install pysamstats
Collecting pysamstats
  Using cached pysamstats-1.1.2.tar.gz (251 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy
  Downloading numpy-1.19.0-cp37-cp37m-manylinux2010_x86_64.whl (14.6 MB)
     |████████████████████████████████| 14.6 MB 145 kB/s
Collecting pysam<0.16
  Using cached pysam-0.15.4-cp37-cp37m-manylinux2010_x86_64.whl (10.7 MB)
Building wheels for collected packages: pysamstats
  Building wheel for pysamstats (PEP 517) ... done
  Created wheel for pysamstats: filename=pysamstats-1.1.2-cp37-cp37m-linux_x86_64.whl size=1055855 sha256=8a9b40f48abcd863e561b414c31d36b491df0e59667bb4c8a65b735c76c07eb6
  Stored in directory: /home/pichauma/.cache/pip/wheels/df/5d/8b/52f192e2bc77fc7673b1763327529c7db87e1162f136f6b9a7
Successfully built pysamstats
Installing collected packages: numpy, pysam, pysamstats
Successfully installed numpy-1.19.0 pysam-0.15.4 pysamstats-1.1.2
```
And

```
> pysamstats
_frozen_importlib:219: RuntimeWarning: pysam.libcalignedsegment.PileupColumn size changed, may indicate binary incompatibility. Expected 72 from C header, got 88 from PyObject
Usage: pysamstats [options] FILE

pysamstats: error: missing SAM or BAM file operand

Try "pysamstats --help" for more information.
```

The same "binary incompatibility" happens with a conda install attempt.

Any idea how to solve that?

Thanks,

M

**Comment by alimanfoo** [comment]
Hi @matthpich, I don't know why conda fails, but the pip failure may be due to pip reusing a cached build of pysam or pysamstats. 

What happens if you start with a completely clean virtual environment, then try:

```
pip install --no-cache-dir pysamstats
```

**Comment by matthpich** [comment]
It works with pip.
Thanks for your help.

For the record, cleaning conda (conda clean -a) before installing pysamstats did not work.

**Comment by alimanfoo** [comment]
No worries. I think I've hit something similar several times, where pip caches a package built using one environment, then tries to reuse and install into a different environment with different versions of dependencies. So confusing.

**Comment by marade** [comment]
I get the same issue, but --no-cache-dir with pip isn't fixing it. Other ideas?

**Comment by marade** [comment]
The same thing happens when I download the latest release, unpack it, and do `pip --no-cache-dir install .`

**Comment by marade** [comment]
...and trying it one more way yields a different error:

pip3 install --upgrade pysam
git clone git://github.com/alimanfoo/pysamstats.git
cd pysamstats/
python3 setup.py install

Traceback (most recent call last):
  File "/usr/local/bin/pysamstats", line 4, in <module>
    __import__('pkg_resources').run_script('pysamstats==1.1.2', 'pysamstats')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/pysamstats-1.1.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/pysamstats", line 10, in <module>
    import pysamstats
  File "/usr/local/lib/python3.6/dist-packages/pysamstats-1.1.2-py3.6-linux-x86_64.egg/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/usr/local/lib/python3.6/dist-packages/pysamstats-1.1.2-py3.6-linux-x86_64.egg/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "pysamstats/opt.pyx", line 1, in init pysamstats.opt
AttributeError: module 'pysam.libcalignmentfile' has no attribute 'IteratorColumnAll'
