### ISSUE TITLE
setup.py should check for pysam==0.8.0

### ISSUE THREAD

**Issue by iosonofabio** [alimanfoo/pysamstats#39]
Hi,

I see you put various install checks in setup.py, I think there should be one for pysam 0.8.0. 0.7 won't work, and 0.8.1 neither (yet).

Otherwise the user gets mysterious Cython errors and it takes a while to figure it's just the wrong pysam version.

Thx
F

**Comment by alimanfoo** [comment]
pysamstats v0.21 supports pysam 0.8.1.

I've added an install_requires keyword argument to setup(), however this doesn't prevent compile errors from occurring if pysam 0.8.0 or earlier is present on the system, as the compilation step occurs before pip checks for install requirements.

I tried using the setup_requires keyword argument, however I believe this results in pysam getting downloaded and installed twice without much feedback to the user, which leads to a long and rather opaque install process. So I've removed the setup_requires argument, I think the best option in general is to manually install dependencies before installing pysamstats.

On the [GitHub README](https://github.com/alimanfoo/pysamstats/blob/master/README.md) I've tried to add some careful documentation about how to install, hopefully this will avoid too much install pain.
