### ISSUE TITLE
pip install error on Python 2.7.6

### ISSUE THREAD

**Issue by IndyMark** [alimanfoo/pysamstats#43]
pip freeze shows all of the prerequisites installed as recommended:
Cython==0.22
numpy==1.9.2
pysam==0.8.1

[root@harvest03 ~]# pip install pysamstats
Downloading/unpacking pysamstats
  Downloading pysamstats-0.21.tar.gz (259kB): 259kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pysamstats/setup.py) egg_info for package pysamstats
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pysamstats/setup.py", line 21, in <module>
        include_dirs=pysam.get_include(),
    AttributeError: 'module' object has no attribute 'get_include'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pysamstats/setup.py", line 21, in <module>

    include_dirs=pysam.get_include(),

AttributeError: 'module' object has no attribute 'get_include'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pysamstats
Storing debug log for failure in /root/.pip/pip.log
[root@harvest03 ~]#

Any ideas?

**Comment by alimanfoo** [comment]
Hi @IndyMark, I'm sorry I don't know what's causing your problem, I just tried installing cython, numpy and pysam in an isolated virtual environment under Python 2.7.8 on my Ubuntu box and everything went fine.

The error suggests that for some reason pip is importing a different version of pysam from the one you installed. Are you installing within a virtual environment? Are there any previous versions of pysam installed in the venv or system-wide?

**Comment by IndyMark** [comment]
Thanks for your help.  I am by no means a python expert, but your response got me pointed in the right direction at least.  The problem was with pysam.  Although I installed pysam 0.8.1, after debugging the setup script I realized that there were other (old) pysams installed as "sub-packages" with other python modules, specifically CPAT and RSeQC.  I performed a pip uninstall of CPAT and RSeQC and after doing that, I was able to successfully install pysamstats.

**Comment by alimanfoo** [comment]
No worries, glad you got it sorted. Getting a Python environment set up
right can be surprisingly tricky, especially when Cython is involved.

On Wed, Apr 22, 2015 at 7:57 PM, IndyMark <notifications@github.com> wrote:

> Thanks for your help. I am by no means a python expert, but your response
> got me pointed in the right direction at least. The problem was with pysam.
> Although I installed pysam 0.8.1, after debugging the setup script I
> realized that there were other (old) pysams installed as "sub-packages"
> with other python modules, specifically CPAT and RSeQC. I performed a pip
> uninstall of CPAT and RSeQC and after doing that, I was able to
> successfully install pysamstats.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/43#issuecomment-95302684>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721
