### ISSUE TITLE
Control threads?

### ISSUE THREAD

**Issue by ONeillMB1** [alimanfoo/pysamstats#44]
Is there a way to control the number of threads the program uses?

**Comment by ONeillMB1** [comment]
Nevermind - Yesterday it appeared that the program was running on multiple threads, however I believe it was just a fluke because when I just tried it again today it only used one.

**Comment by alimanfoo** [comment]
Yes pysamstats is single threaded.

On Wednesday, 1 July 2015, ONeillMB1 <notifications@github.com> wrote:

> Nevermind - Yesterday it appeared that the program was running on multiple
> threads, however I believe it was just a fluke because when I just tried it
> again today it only used one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/44#issuecomment-117722868>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721
