### ISSUE TITLE
pysamstats fails on smalt and bowtie2 bam files

### ISSUE THREAD

**Issue by Takadonet** [alimanfoo/pysamstats#46]
Getting the following stacktrace when running on either smalt or bowtie2 bam file : 
pysamstats sorted.bam

chrom	pos	reads_all	reads_pp
Traceback (most recent call last):
  File "/usr/local/bin/pysamstats", line 231, in <module>
    fields=fields,
  File "pysamstats.pyx", line 3926, in pysamstats.write_csv (pysamstats.c:38831)
  File "pysamstats.pyx", line 4121, in genexpr (pysamstats.c:41238)
  File "pysamstats.pyx", line 3693, in _iter_pileup_default (pysamstats.c:34936)
TypeError: Argument 'col' has incorrect type (expected pysam.calignmentfile.PileupColumn, got pysam.calignedsegment.PileupColumn)

Running on xubuntu 14.0.4
pysam 0.8.4
python 2.7.6
pysam 0.24.0

**Comment by alimanfoo** [comment]
Thanks Philip, this looks like I didn't fully fix things after the pysam
upgrade, will try and sort asap.

On Tue, Dec 8, 2015 at 3:35 PM, Philip Mabon <notifications@github.com>
wrote:

> Getting the following stacktrace when running on either smalt or bowtie2
> bam file :
> pysamstats sorted.bam
>
> chrom pos reads_all reads_pp
> Traceback (most recent call last):
> File "/usr/local/bin/pysamstats", line 231, in
> fields=fields,
> File "pysamstats.pyx", line 3926, in pysamstats.write_csv
> (pysamstats.c:38831)
> File "pysamstats.pyx", line 4121, in genexpr (pysamstats.c:41238)
> File "pysamstats.pyx", line 3693, in _iter_pileup_default
> (pysamstats.c:34936)
> TypeError: Argument 'col' has incorrect type (expected
> pysam.calignmentfile.PileupColumn, got pysam.calignedsegment.PileupColumn)
>
> Running on xubuntu 14.0.4
> pysam 0.8.4
> python 2.7.6
> pysam 0.24.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/46>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by Takadonet** [comment]
Thanks!

**Comment by alimanfoo** [comment]
@Takadonet I've just made a new release, 0.24.1, would you mind checking it fixes this bug? Thanks.

**Comment by Takadonet** [comment]
Works. thanks for the quick patch!

**Comment by alimanfoo** [comment]
Great, thanks for reporting.
