### ISSUE TITLE
Variation stats are broken in PY3

### ISSUE THREAD

**Issue by TizianoGC** [alimanfoo/pysamstats#48]
Hi Alistair,

From Python 3, I'm using pysamstats 0.24.1 and pysam 0.8.4 installed with pip3.
In case a string is given to the option "chrom", the "load_variation" function raises: 
"TypeError: decoding str is not supported"
If possible, could you please change these functions, if this problem is common to others like "load_coverage", so they accept a string as well? I never had this problem with past versions and it would really help me a lot to be still able to use strings for filtering chromosomes.

Cheers,
Tiziano

**Comment by alimanfoo** [comment]
Thanks Tiziano, I'll look into it asap.

On Tue, Jan 19, 2016 at 6:27 PM, TizianoGC <notifications@github.com> wrote:

> Hi Alistair,
>
> From Python 3, I'm using pysamstats 0.24.1 and pysam 0.8.4 installed with
> pip3.
> In case a string is given to the option "chrom", the "load_variation"
> function raises:
> "TypeError: decoding str is not supported"
> If possible, could you please change these functions, if this problem is
> common to others like "load_coverage", so they accept a string as well? I
> never had this problem with past versions and it would really help me a lot
> to be still able to use strings for filtering chromosomes.
>
> Cheers,
> Tiziano
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/48>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Just to confirm 0.24.1 is broken, there was a mistake in my dev setup that meant it didn't get tested properly before release. Fixing now.

**Comment by alimanfoo** [comment]
Should be fixed, problem was due to change in latest pysam where fafile.fetch() now returns str. Also uncovered a couple of other bugs related to pysam changes.

**Comment by alimanfoo** [comment]
Fix is in new release 0.24.2. @TizianoGC I'd be very grateful if you could do a pip upgrade and confirm this is fixed for you.

**Comment by TizianoGC** [comment]
Thank you Alistair, I'll write back to you as soon as it will be upgraded in my environment (unfortunately I can't do it by myself at the moment)

**Comment by TizianoGC** [comment]
The bug is now fixed for me; thank you for the quick fix!

**Comment by alimanfoo** [comment]
Great! Thanks for the bug report.

On Thu, Jan 21, 2016 at 12:08 PM, TizianoGC <notifications@github.com>
wrote:

> The bug is now fixed for me; thank you for the quick fix!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/48#issuecomment-173552407>
> .
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721
