### ISSUE TITLE
coverage status excluding deletions

### ISSUE THREAD

**Issue by psudmant** [alimanfoo/pysamstats#50]
It would be extremely helpful to be able to exclude deletions with the load_coverage function. In RNA-seq data there are often split reads spanning big gaps that you really don't want to count. load_variation is a little bit overkill for this case. 

Great package, cheers!

**Comment by alimanfoo** [comment]
Thanks Peter, should be straightforward to add this.

On Thursday, 28 January 2016, Peter Sudmant <notifications@github.com>
wrote:

> It would be extremely helpful to be able to exclude deletions with the
> load_coverage function. In RNA-seq data there are often split reads
> spanning big gaps that you really don't want to count. load_variation is a
> little bit overkill for this case.
>
> Great package, cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/50>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by psudmant** [comment]
Hey there, has there been any updates on this? I wrote a super ugly hack around it, but, it woudl be great to have a cleaner solution. 

Thanks!

**Comment by alimanfoo** [comment]
Hi Peter, apologies, I've been snowed under.

One question, do you have any thoughts on how this should be fitted into
the existing API? I've mulled this over a bit but haven't settled on
anything.

E.g., how about adding a "reads_nodel" field to the "coverage_ext"
statistics type? Would you also want "reads_nodel_pp"?

Thanks.

On Tuesday, June 14, 2016, Peter Sudmant <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Hey there, has there been any updates on this? I wrote a super ugly hack
> around it, but, it woudl be great to have a cleaner solution.
>
> Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/50#issuecomment-225989039>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAq8Qky_Yj7KTk4_usB1hq5R5xM5RZysks5qLv_lgaJpZM4HN8N8>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by psudmant** [comment]
no worries!

I suppose my approach would be a bit different, I would simply add a flag that's passed to stat_coverage. Then when I get the coverage, I get reads_all and reads_pp, but, I've flipped the "no_del" flag. 

What do you think?

**Comment by alimanfoo** [comment]
Yep that's the other option. I'm a bit reluctant to go down that route
however as it would require changing the behaviour of all of the existing
statistics types to keep things consistent, which would be a fairly big
change. I thought it would be more straightforward to add some new fields
into the existing stats types with the nodel semantics. It would also be
clear for anyone exchanging files generated by pysamstats, i.e.,
"reads_all" would always mean the same thing, you wouldn't need to know
whether pysamstats was run with the "nodel" flag or not.

On Wednesday, June 15, 2016, Peter Sudmant <notifications@github.com> wrote:

> no worries!
>
> I suppose my approach would be a bit different, I would simply add a flag
> that's passed to stat_coverage. Then when I get the coverage, I get
> reads_all and reads_pp, but, I've flipped the "no_del" flag.
>
> What do you think?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/50#issuecomment-226250789>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAq8Qi0EF7u3M2Xp1AII5or3dp7LhNoRks5qMC8SgaJpZM4HN8N8>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by psudmant** [comment]
Yes, I noticed this EXACT thing when I tried to modify the code. Well, perhaps for now we should go with your option and the other approach would be good to think about for v2.0 :). 

Thanks much!

Cheers

**Comment by alimanfoo** [comment]
OK, thanks for the discussion, helps a lot.

On Wednesday, June 15, 2016, Peter Sudmant <notifications@github.com> wrote:

> Yes, I noticed this EXACT thing when I tried to modify the code. Well,
> perhaps for now we should go with your option and the other approach would
> be good to think about for v2.0 :).
>
> Thanks much!
>
> Cheers
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/50#issuecomment-226263686>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAq8QlA4n-3xLy0BOHD3KFWwSJzWlOp9ks5qMDmRgaJpZM4HN8N8>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
In #67 added a "no_del" option to all pileup-based stats, which filters out all reads aligned with a deletion at the current position.
