### ISSUE TITLE
Unclear Cython installation instructions

### ISSUE THREAD

**Issue by fourpartswater** [alimanfoo/pysamstats#51]
I just wasted an hour hacking around trying to solve this problem:
## In [1]: import pysamstats

ValueError                                Traceback (most recent call last)
<ipython-input-1-99f71b0dc7b5> in <module>()
----> 1 import pysamstats

cfaidx.pxd in init pysamstats (pysamstats.c:50654)()

ValueError: pysam.cfaidx.FastaFile has the wrong size, try recompiling

before I realised that you had a precythonized C file in the main directory - stupid of me I know. I removed pysamstats.c and everything was fine. Maybe you could have this as a warning in the installation instructions? Or have a recompilation step in setup if you see someone has cython and different version of pysam?

Otherwise, great work! 

Peter

**Comment by alimanfoo** [comment]
Thanks Peter, very sorry you had any bother. Can I just ask, how were you
trying to install pysamstats?

On Monday, February 22, 2016, Peter Clarke <notifications@github.com> wrote:

> I just wasted an hour hacking around trying to solve this problem:
> In [1]: import pysamstats
>
> ValueError Traceback (most recent call last)
> in ()
> ----> 1 import pysamstats
>
> cfaidx.pxd in init pysamstats (pysamstats.c:50654)()
>
> ValueError: pysam.cfaidx.FastaFile has the wrong size, try recompiling
>
> before I realised that you had a precythonized C file in the main
> directory - stupid of me I know. I removed pysamstats.c and everything was
> fine. Maybe you could have this as a warning in the installation
> instructions? Or have a recompilation step in setup if you see someone has
> cython and different version of pysam?
>
> Otherwise, great work!
>
> Peter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/51>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by fourpartswater** [comment]
Hi,

I was installing pysam and pysamstats from Github as I am trying to use
some recent cythonized BCF code from pysam that is under development at the
moment.

The way things are going it would be goof to make sure that the github
versions of pysam and pysamstats are compatible

I would not have spent so much time on it if it wasn't so useful!

Thanks!

Peter

**Comment by alimanfoo** [comment]
Thanks Peter. FWIW for development, I have a virtualenv with the version of
pysam that I want to build against, then assuming current working dir is
pysamstats repo root, I do:

python cythonize.py
python setup.py build_ext --inplace

Test suite can then be run with nosetests.

I've tweaked the github readme but let me know if you think there's any
info missing.

It would be good to keep pysamstats and pysam in sync, if you find any
problems let me know. I have tended to wait for a minor version release,
things have been in flux a lot through the 0.8.x series. Pretty much every
minor version release there has been a breaking change to the cython API,
I'm not grumbling because they're doing great work on pysam but it will be
nice when things settle down.

On Tuesday, February 23, 2016, Peter Clarke <notifications@github.com>
wrote:

> Hi,
>
> I was installing pysam and pysamstats from Github as I am trying to use
> some recent cythonized BCF code from pysam that is under development at the
> moment.
>
> The way things are going it would be goof to make sure that the github
> versions of pysam and pysamstats are compatible
>
> I would not have spent so much time on it if it wasn't so useful!
>
> Thanks!
>
> Peter
>
> On 22 February 2016 at 21:42, Alistair Miles <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Thanks Peter, very sorry you had any bother. Can I just ask, how were you
> > trying to install pysamstats?
> >
> > On Monday, February 22, 2016, Peter Clarke <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > I just wasted an hour hacking around trying to solve this problem:
> > > In [1]: import pysamstats
> > >
> > > ValueError Traceback (most recent call last)
> > > in ()
> > > ----> 1 import pysamstats
> > >
> > > cfaidx.pxd in init pysamstats (pysamstats.c:50654)()
> > >
> > > ValueError: pysam.cfaidx.FastaFile has the wrong size, try recompiling
> > >
> > > before I realised that you had a precythonized C file in the main
> > > directory - stupid of me I know. I removed pysamstats.c and everything
> > was
> > > fine. Maybe you could have this as a warning in the installation
> > > instructions? Or have a recompilation step in setup if you see someone
> > has
> > > cython and different version of pysam?
> > >
> > > Otherwise, great work!
> > >
> > > Peter
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/alimanfoo/pysamstats/issues/51>.
> > >
> >
> >
> > --
> > Alistair Miles
> > Head of Epidemiological Informatics
> > Centre for Genomics and Global Health <http://cggh.org>
> > The Wellcome Trust Centre for Human Genetics
> > Roosevelt Drive
> > Oxford
> > OX3 7BN
> > United Kingdom
> > Email: alimanfoo@googlemail.com
> <javascript:_e(%7B%7D,'cvml','alimanfoo@googlemail.com');> <
> alimanfoo@gmail.com <javascript:_e(%7B%7D,'cvml','alimanfoo@gmail.com');>>
> > Web: http://purl.org/net/aliman
> > Twitter: https://twitter.com/alimanfoo
> > Tel: +44 (0)1865 287721
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/alimanfoo/pysamstats/issues/51#issuecomment-187399215>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/51#issuecomment-187633201>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by fourpartswater** [comment]
Hi Alistair,

One solution that I have seen with other repos is to only supply the .c
file with releases (pypi/conda/release tags etc) and require cython for
master checkout from github. Then you can stick the cythonizing (new word?)
into setup.py if the .c isn't there.

Thanks for your quick responses!

Cheers,

Peter

**Comment by alimanfoo** [comment]
That's a good idea, I think I'll switch to that.

Cheers,
Alistair

On Tuesday, February 23, 2016, Peter Clarke <notifications@github.com>
wrote:

> Hi Alistair,
>
> One solution that I have seen with other repos is to only supply the .c
> file with releases (pypi/conda/release tags etc) and require cython for
> master checkout from github. Then you can stick the cythonizing (new word?)
> into setup.py if the .c isn't there.
>
> Thanks for your quick responses!
>
> Cheers,
>
> Peter
>
>
>
> On 23 February 2016 at 21:21, Alistair Miles <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Thanks Peter. FWIW for development, I have a virtualenv with the version
> of
> > pysam that I want to build against, then assuming current working dir is
> > pysamstats repo root, I do:
> >
> > python cythonize.py
> > python setup.py build_ext --inplace
> >
> > Test suite can then be run with nosetests.
> >
> > I've tweaked the github readme but let me know if you think there's any
> > info missing.
> >
> > It would be good to keep pysamstats and pysam in sync, if you find any
> > problems let me know. I have tended to wait for a minor version release,
> > things have been in flux a lot through the 0.8.x series. Pretty much
> every
> > minor version release there has been a breaking change to the cython API,
> > I'm not grumbling because they're doing great work on pysam but it will
> be
> > nice when things settle down.
> >
> > On Tuesday, February 23, 2016, Peter Clarke <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Hi,
> > >
> > > I was installing pysam and pysamstats from Github as I am trying to use
> > > some recent cythonized BCF code from pysam that is under development at
> > the
> > > moment.
> > >
> > > The way things are going it would be goof to make sure that the github
> > > versions of pysam and pysamstats are compatible
> > >
> > > I would not have spent so much time on it if it wasn't so useful!
> > >
> > > Thanks!
> > >
> > > Peter
> > >
> > > On 22 February 2016 at 21:42, Alistair Miles <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > Thanks Peter, very sorry you had any bother. Can I just ask, how were
> > you
> > > > trying to install pysamstats?
> > > >
> > > > On Monday, February 22, 2016, Peter Clarke <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> >
> > > > wrote:
> > > >
> > > > > I just wasted an hour hacking around trying to solve this problem:
> > > > > In [1]: import pysamstats
> > > > >
> > > > > ValueError Traceback (most recent call last)
> > > > > in ()
> > > > > ----> 1 import pysamstats
> > > > >
> > > > > cfaidx.pxd in init pysamstats (pysamstats.c:50654)()
> > > > >
> > > > > ValueError: pysam.cfaidx.FastaFile has the wrong size, try
> > recompiling
> > > > >
> > > > > before I realised that you had a precythonized C file in the main
> > > > > directory - stupid of me I know. I removed pysamstats.c and
> > everything
> > > > was
> > > > > fine. Maybe you could have this as a warning in the installation
> > > > > instructions? Or have a recompilation step in setup if you see
> > someone
> > > > has
> > > > > cython and different version of pysam?
> > > > >
> > > > > Otherwise, great work!
> > > > >
> > > > > Peter
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/alimanfoo/pysamstats/issues/51>.
> > > > >
> > > >
> > > >
> > > > --
> > > > Alistair Miles
> > > > Head of Epidemiological Informatics
> > > > Centre for Genomics and Global Health <http://cggh.org>
> > > > The Wellcome Trust Centre for Human Genetics
> > > > Roosevelt Drive
> > > > Oxford
> > > > OX3 7BN
> > > > United Kingdom
> > > > Email: alimanfoo@googlemail.com
> <javascript:_e(%7B%7D,'cvml','alimanfoo@googlemail.com');>
> > > <javascript:_e(%7B%7D,'cvml','alimanfoo@googlemail.com
> <javascript:_e(%7B%7D,'cvml','alimanfoo@googlemail.com');>');> <
> > > alimanfoo@gmail.com
> <javascript:_e(%7B%7D,'cvml','alimanfoo@gmail.com');>
> <javascript:_e(%7B%7D,'cvml','alimanfoo@gmail.com
> <javascript:_e(%7B%7D,'cvml','alimanfoo@gmail.com');>
> > ');>>
> > > > Web: http://purl.org/net/aliman
> > > > Twitter: https://twitter.com/alimanfoo
> > > > Tel: +44 (0)1865 287721
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> https://github.com/alimanfoo/pysamstats/issues/51#issuecomment-187399215
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/alimanfoo/pysamstats/issues/51#issuecomment-187633201
> >
> >
> > > .
> > >
> >
> >
> > --
> > Alistair Miles
> > Head of Epidemiological Informatics
> > Centre for Genomics and Global Health <http://cggh.org>
> > The Wellcome Trust Centre for Human Genetics
> > Roosevelt Drive
> > Oxford
> > OX3 7BN
> > United Kingdom
> > Email: alimanfoo@googlemail.com
> <javascript:_e(%7B%7D,'cvml','alimanfoo@googlemail.com');> <
> alimanfoo@gmail.com <javascript:_e(%7B%7D,'cvml','alimanfoo@gmail.com');>>
> > Web: http://purl.org/net/aliman
> > Twitter: https://twitter.com/alimanfoo
> > Tel: +44 (0)1865 287721
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/alimanfoo/pysamstats/issues/51#issuecomment-187915405>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/51#issuecomment-187930168>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Leaving this open as a reminder to remove .c file from GitHub repo and modify setup.py to cythonize if .c not present.

**Comment by alimanfoo** [comment]
Have left .c file but setup.py now will cythonize if cython is present.
