### ISSUE TITLE
base-quality threshold

### ISSUE THREAD

**Issue by frabanal** [alimanfoo/pysamstats#53]
Great tool! 
I would find particularly useful to implement a minimum base quality threshold to compute statistics only from those bases that passed it. 
Or is there such an argument that I haven't noticed?
Kind regards.

**Comment by alimanfoo** [comment]
Thanks! There is no support currently for filtering by base quality. This
should be possible to add and I'd be happy to look into it, but I'm a bit
tied up for the next month or so can't promise a quick turn-around I'm
afraid.

On Thursday, April 7, 2016, frabanal <notifications@github.com> wrote:

> Great tool!
> I would find particularly useful to implement a minimum base quality
> threshold to compute statistics only from those bases that passed it.
> Or is there such an argument that I haven't noticed?
> Kind regards.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/53>
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Implemented via #67.
