### ISSUE TITLE
Distinguishing block indels from single indels

### ISSUE THREAD

**Issue by astewart-twist** [alimanfoo/pysamstats#54]
Hi @alimanfoo.  Wondering if I can just get your opinion on something:

pysamstats/pysam/samtools_pileup is great for tabulating alignment statistics within the narrow context of a pileup column, but from a bio/chem perspective it would be useful to be able to separate single indels (length = 1) from block indels (length > 1).  I'm trying to see if I can hack along the pysamstats/pysam stack to this end.  

At first I thought this might not be practical to do using pysam pileup (and therefore pysamstats too), but I found something in the documentation that gives me hope: http://pysam.readthedocs.io/en/latest/api.html#pysam.PileupRead.indel 

> **indel**
> 
> indel length for the position follwing the current pileup site.
> 
> This quantity peeks ahead to the next cigar operation in this alignment. If the next operation is and insertion, indel will be positve. If the next operation is a deletion, it will be negation. 0 if the next operation is not an indel.

That seems to indicate to me that it might be possible to determine whether an insertion or deletion at a given position is a single indel or part of a larger block indel.

Does that sound correct to you, or am I way off?  If it's true, then it seems to me I could potentially modify pysamstats to split the deletions count into single indels and block indels.

**Comment by astewart-twist** [comment]
I think I see where in pysamstats this could be done:

https://github.com/alimanfoo/pysamstats/blob/43435f3982b265129375991b3bfd0f78c34c9e63/pysamstats.pyx#L807

```
            if read.indel > 0:
                insertions += 1
```

It looks like I could just differentiate based on the value of read.indel like so?

```
            if read.indel == 1:
                single_insertions += 1
            elif read.indel > 1
                block_insertions += 1
```

**Comment by alimanfoo** [comment]
Hi there, yes that's it, I believe the read.indel property has the length
of the insertion (or deletion of negative).

On Thursday, 2 June 2016, astewart-twist <notifications@github.com> wrote:

> I think I see where in pysamstats this could be done:
>
>
> https://github.com/alimanfoo/pysamstats/blob/43435f3982b265129375991b3bfd0f78c34c9e63/pysamstats.pyx#L807
>
>             if read.indel > 0:
>                 insertions += 1
>
> It looks like I could just differentiate based on the value of read.indel
> like so?
>
>             if read.indel == 1:
>                 single_insertions += 1
>             elif read.indel > 1
>                 block_insertions += 1
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/54#issuecomment-223188360>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAq8QoLaV7bpeBwLWLYvK45SCD1lu4Voks5qHlHpgaJpZM4IsHZb>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by astewart-twist** [comment]
Thanks @alimanfoo.  I can make a fork and try it out.  I expect I will also have to make some other changes to accommodate the addition of extra fields in the output?  Maybe some other changes I'm not aware of?

Any chance you can give me a an idea of where else I would have to make those changes?

**Comment by alimanfoo** [comment]
Hi there, apologies for the slow response, just back from a conference.
Here's some info in case it's still useful.

Assuming you do this by modifying the existing "variation" statistics
output, all the relevant functions are within the "VARIATION STATISTICS"
section within pysamstats.pyx. You would need to modify the following
variables and functions:

dtype_variation
_rec_variation
_rec_variation_pad

That *should* be all you need to do.

To compile pysamstats is currently a two-step process. Step 1, from the
repo root dir, run:

python cythonize.py

Step 2a, build in-place:

python setup.py build_ext --inplace

Step 2b, alternatively build and install:

python setup.py install

Hth,
Alistair

On Thursday, June 2, 2016, astewart-twist <notifications@github.com> wrote:

> Thanks @alimanfoo <https://github.com/alimanfoo>. I can make a fork and
> try it out. I expect I will also have to make some other changes to
> accommodate the addition of extra fields in the output? Maybe some other
> changes I'm not aware of?
>
> Any chance you can give me a an idea of where else I would have to make
> those changes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/alimanfoo/pysamstats/issues/54#issuecomment-223354381>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAq8QhJOyeCHFHT3GNOR27wCqEbuHMw1ks5qHwulgaJpZM4IsHZb>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Closing but feel free to re-open if still relevant.
