### ISSUE TITLE
Spliced reads being counted as deletions

### ISSUE THREAD

**Issue by saldit** [alimanfoo/pysamstats#65]
Hello,

I am using pysamstats to score RNA structure by counting chemical induced modifications, which look like sequence variations in the reads (mismatches, small deletions and insertions).  Your program is working great for this application.  However, one problem I am running into is that the program is counting spliced reads as regions with deletions (which is throwing off my counts).  The reads that are spliced do have the correct CIGAR note for a splice (N) and not a deletion (D). I also noticed that the program is counting the splice as "coverage", falsely increasing the depth of these positions. Is there anyway to work around this so I can get accurate counts that exclude positions over a splice from being counted as a deletion or coverage?

Thanks!

**Comment by alimanfoo** [comment]
This was resolved via #68.

**Comment by saldit** [comment]
Hello- Thank you so much for addressing the above issue.  I did want to make a quick note- while spliced reads are no longer being counted as deletions (which is great) the region covered by the splice junction is still being counted as coverage.  Is there a way to fix this or add an option to fix this?  I am calculating mutations/coverage to get a percent mutated.  When the spliced interval is counted as coverage it artificially deflates the mutated percent.  Thank you.
