### ISSUE TITLE
Ignore masked regions

### ISSUE THREAD

**Issue by KristinaGagalova** [alimanfoo/pysamstats#80]
Hi, 
I am usually hard masking for repeats and afterwards aligning my reads.
I was wondering if you can make an option to distinguish between 0 counts because of a drop of coverage or 0 counts because the region is masked with Ns. 
This can greatly help for when considering read depth analysis such as CNV.
Thanks 
Kristina

**Comment by alimanfoo** [comment]
Hi Kristina,

I usually use [pyfasta](https://pypi.org/project/pyfasta/) for that, e.g.:

```python
import numpy as np
import pyfasta
genome = pyfasta.Fasta('/path/to/your/genome.fa', key_fn=lambda v: v.split()[0])
print(sorted(genome.keys()))  # will show list of chromosomes
chrom = 'Pf3D7_01_v3'  # name of chromosome to work with
seq = np.asarray(genome[chrom])  # this will be  a numpy array of nucleotides
loc_not_masked = seq != b'N'  # Boolean array locating non-masked positions
import pysamstats
mybam = pysam.AlignmentFile('/path/to/your/bamfile.bam')
a = pysamstats.load_coverage(mybam, chrom=chrom, pad=True)
a_not_masked = a[loc_not_masked]  # filter data to exclude masked positions
```

Hth.

**Comment by KristinaGagalova** [comment]
Looks good! Thank you for sharing

**Comment by KristinaGagalova** [comment]
Looks good! Thank you for sharing

**Comment by alimanfoo** [comment]
No problem.
