### ISSUE TITLE
report doesn't include some of the ref sequences, is there a limit?

### ISSUE THREAD

**Issue by prishly** [alimanfoo/pysamstats#81]
My reference fasta file has 52 sequences in it, but there are only 10 in the report generated by pysamstats with -t option set to variation. Is there a limit for the number of reference sequences?

**Comment by prishly** [comment]
Thanks, it's the name length. My reference sequences are actually gene regions, most names are longer than 12 and only differ in the last numeric characters

**Comment by prishly** [comment]
This is weird. Even with much shorter names, the report contains only 10 unique chromosome names instead of 52...

**Comment by alimanfoo** [comment]
OK, cool. FWIW if you need to you can override the dtype for the chrom field, e.g., you can pass something like ``dtype={'chrom': 'a30'}`` into functions in the pysamstats API.  There is also an open PR (#74) to automatically adjust the chrom dtype length, but hasn't been merged yet.

**Comment by alimanfoo** [comment]
Pysamstats gets chromosome names I think from the BAM file, so just editing the FASTA may not change the pysamstats output?

**Comment by alimanfoo** [comment]
Suggest trying to override the dtype.

**Comment by prishly** [comment]
I re-built BAM from scratch, it didn't work. Are you sure it's the name length?

**Comment by prishly** [comment]
... When I left 10 refs in the fasta file, the report only contained 2 ....

**Comment by prishly** [comment]
Oops, sorry, I used the wrong fastq file! Everything's ok, it's my bad. Cool tool!

**Comment by alimanfoo** [comment]
Phew! Glad it's working.
