### ISSUE TITLE
Pysam >= 0.12

### ISSUE THREAD

**Issue by florealcab** [alimanfoo/pysamstats#82]
Hi,

I am using pysamstats for a project, and it's a very nice module!

Unfortunately, this a project is a workflow which implies another software which requires pysam with at least 0.12 version. I tested it with 0.11.2.2 version, and it fails.

I see a merge request which allow using the 0.14 version of pysam for pysamstats. Will be a new release of pysamstats soon, especially for anaconda (I use it to deploy my workflow), soon (in next days?) which will allow pysam 0.14?

**Comment by alimanfoo** [comment]
Hi there, @hardingnj has almost finished that PR but is currently on leave
for a couple of weeks. If you need something in the next few days then you
could install pysamstats from the PR branch. Give me a shout if you need
any help trying that out.

**Comment by alimanfoo** [comment]
Sorry I got confused, the work to make compatible with pysam 0.14 has been
merged into master, so you could try installing from master. There is
another PR outstanding which I'd like to finish before making a new
release.

**Comment by hardingnj** [comment]
This should be done in the next day or so, thanks for your patience!

**Comment by alimanfoo** [comment]
Resolved via #77
