### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by andersgs** [alimanfoo/pysamstats#84]
Hi.

Great tool! Thank you. Unfortunately, `pip install` did not work for me. Pip installing from the github worked fine though. The error tells me Cython can't find `opt.pyx`. 

Thank you.

Anders.

**Comment by alimanfoo** [comment]
Hi Anders, many apologies, I made a mistake in the last release which meant
that the pyx files are not included, although the C files are. During pip
installation it checks if Cython is present then tries to build from pyx,
if not then builds from C. I'll make a new release shortly, but for the
time being you can work around this by uninstalling Cython, installing
pysamstats, then reinstalling Cython.

**Comment by alimanfoo** [comment]
The missing files were resolved via #77. Will make a new release soon.
